---
  title: "Graph Analysis"
author: "Richard"
date: "2017"
output:
  pdf_document: default
html_document: null
toc: yes
toc_depth: yes
word_document: default
---


  Clear environment, load variables, functions and libraries
```{r, include=FALSE}
library(igraph)
library(gplots)
library(ggplot2)

EEGNames = c('Fp1','AF7','AF3','F1','F3','F5','F7','FT7','FC5','FC3','FC1','C1',
             'C3','C5','T7','TP7','CP5','CP3','CP1','P1','P3','P5','P7','P9','PO7',
             'PO3','O1','Lz','Oz','POz','Pz','CPz','Fpz','Fp2','AF8','AF4','AFz','Fz',
             'F2','F4','F6','F8','FT8','FC6','FC4','FC2','FCz','Cz','C2','C4','C6',
             'T8','TP8','CP6','CP4','CP2','P2','P4','P6','P8','P10','PO8','PO4','O2')

bands = c("theta","alpha","beta","gamma")

```

```{r, include=FALSE}
inputlist <- list.files("./Output/",pattern = ".csv")

for (i in inputlist) {
  j = paste("./Output/",i,sep="")
  print(j)
# read csv file
dat=read.csv(j,header=TRUE)

for (b in bands) {
data = subset(dat,select = c('channel_1','channel_2', b))
el=as.matrix(data)
G <- graph.data.frame(el,directed=FALSE);
A <- as_adjacency_matrix(G,type="both",names=TRUE,sparse=FALSE,attr=b)
rownames(A) = EEGNames
colnames(A) = EEGNames
# slightly annoying workaround to make the graph weighted...
temp = graph_from_adjacency_matrix(A, mode = "undirected", weighted = TRUE, diag = FALSE,
  add.colnames = NULL, add.rownames = NULL)
assign((b),temp)

}
}

```

# plotting example
```{r, include=FALSE}
weights <- sort(E(alpha)$weight, decreasing=TRUE)
threshold <- weights[length(weights)*0.2]
g=delete.edges(alpha, which(E(alpha)$weight <=threshold))
plot(g)
```
